DASH_APP:
  APP_TITLE: Frequency Analysis in Hydrology
  HEAD_TITLE: fiako-anfrek | Frequency Analysis in Hydrology
  UPDATE_TITLE: Updating...
  DEBUG: TRUE
  ALIAS: fiako-anfrek

TEMPLATE:
  WATERMARK_SOURCE: 
  THEME: FLATLY

VERSION: v1.2.0
GITHUB_LINK: https://github.com/taruma/anfrek
GITHUB_REPO: taruma/anfrek
